/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: keiichiisozaki (https://sketchfab.com/keiichiisozaki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/substance-miku-c82070799db14f2088691e6cd0195001
Title: Substance Miku
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from "gsap"
import { useThree } from '@react-three/fiber'
import ScrollTrigger from 'gsap/ScrollTrigger'


export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  let camera = useThree((state) => state.camera)
  let scene = useThree((state) => state.scene)
  const group = useRef()

  useLayoutEffect(() => {
    gsap.fromTo(scene.position, {x:0,y:-1200,z:0}, {z:-1700, y:-1100, x:-400})
    gsap.to(scene.rotation, {y: -1.5})

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: "#girl-model",
        start: "top top",
        scrub: 1,
        endTrigger: "#endTrigger"
      }
    })

    
    tl.to(scene.position, {x: 600}, "key1")
      .to(scene.rotation, {y: 4}, "key1")
      .to(scene.position, {z: -2900}, "")
      .to(scene.rotation, {y: 4.5})
    
    //  gsap.fromTo(scene.position, {x:0,y:-1200,z:0}, {z:-1700, y:-1100, x:-400})
    //   gsap.to(scene.rotation, {y: -1.5})

    return () => {
      initialPosition.kill();
      initialRotation.kill();
      tl.kill();
      ScrollTrigger.getAll().forEach(trigger => trigger.kill());
    };
    
  }, [scene])



  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={3.422}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.skin_skin_0.geometry} material={materials.skin} />
            <mesh geometry={nodes.skin_eye_0.geometry} material={materials.material} />
          </group>
          <mesh geometry={nodes.emerald001_emerald_0.geometry} material={materials.emerald} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.skin002_skin_0.geometry} material={materials.skin} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.twintail000_hair_0.geometry} material={materials.hair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.bangs_hair_0.geometry} material={materials.hair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.cloth003_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube002_acce_0.geometry} material={materials.acce} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.hair_hair_0.geometry} material={materials.hair} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.face_eye_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.face001_spec_0.geometry} material={materials.spec} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cube001_acce_0.geometry} material={materials.acce} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.emerald_emerald_0.geometry} material={materials.emerald} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane010_skin_0.geometry} material={materials.skin} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane007_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane005_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane001_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.tie_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane004_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane003_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane002_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane_cloth_0.geometry} material={materials.cloth} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
